import json
import sys

def to_go_type(prop):
    t = prop.get('type')
    if t == 'string':
        return 'string'
    if t == 'number':
        return 'float64'
    if t == 'integer':
        return 'int'
    if t == 'boolean':
        return 'bool'
    if t == 'array':
        items = prop.get('items', {})
        return '[]' + to_go_type(items)
    return 'interface{}'

def go_field(name):
    parts = name.split('_')
    return ''.join(p.capitalize() for p in parts)

def gen_struct(name, props, required):
    lines = [f"type {name} struct {{"]
    for field, prop in props.items():
        typ = to_go_type(prop)
        if field not in required:
            typ = '*' + typ
        lines.append(f"    {go_field(field)} {typ} `json:\"{field}\"`")
    lines.append("}")
    return "\n".join(lines)

with open('device_types.json') as f:
    data = json.load(f)

traits = data.get('traits', {})
types = data.get('types', {})

out = []
out.append("// Code generated by gen_go.py; DO NOT EDIT.\n")
out.append("package device\n")

for name, tdef in traits.items():
    out.append(gen_struct(go_field(name), tdef.get('properties', {}), tdef.get('required', [])))
    out.append("")

for name, tdef in types.items():
    all_props = {}
    all_req = []
    for trait in tdef.get('traits', []):
        if trait in traits:
            all_props.update(traits[trait].get('properties', {}))
            all_req.extend(traits[trait].get('required', []))
    extra = tdef.get('extra_schema', {})
    all_props.update(extra.get('properties', {}))
    all_req.extend(extra.get('required', []))
    out.append(gen_struct(go_field(name), all_props, all_req))
    out.append("")

with open('../../../services/layout/internal/filters/device_types.go', 'w') as f:
    f.write("\n".join(out))

