import json

def to_go_type(prop):
    t = prop.get('type')
    if t == 'string':
        return 'string'
    if t == 'number':
        return 'float64'
    if t == 'integer':
        return 'int'
    if t == 'boolean':
        return 'bool'
    if t == 'array':
        items = prop.get('items', {})
        return '[]' + to_go_type(items)
    return 'interface{}'

def go_field(name):
    parts = name.split('_')
    return ''.join(p.capitalize() for p in parts)

def collect_filterable_props(tdef, traits):
    props = {}
    for trait_name in tdef.get('traits', []):
        trait = traits.get(trait_name, {})
        for prop_name, prop_schema in trait.get('properties', {}).items():
            if prop_schema.get('filterable'):
                props[prop_name] = prop_schema
    extra = tdef.get('extra_schema', {}).get('properties', {})
    for prop_name, prop_schema in extra.items():
        if prop_schema.get('filterable'):
            props[prop_name] = prop_schema
    return props

with open('device_types.json') as f:
    data = json.load(f)

traits = data.get('traits', {})
types = data.get('types', {})

out = []
out.append("// Code generated by gen_filters.py; DO NOT EDIT.\n")
out.append("package filters\n\n")
out.append("type DeviceFilter interface{}\n\n")

for type_name, tdef in types.items():
    filterable = collect_filterable_props(tdef, traits)
    struct_name = go_field(type_name) + "Filter"
    if not filterable:
        out.append(f"type {struct_name} struct {{}}\n")
    else:
        lines = [f"type {struct_name} struct {{"]
        for field, prop in filterable.items():
            typ = to_go_type(prop)
            lines.append(f"    {go_field(field)} {typ} `json:\"{field},omitempty\"`")
        lines.append("}")
        out.append("\n".join(lines))
    out.append("")

output_path = '../../../services/layout/internal/filters/filters_gen.go'
with open(output_path, 'w') as f:
    f.write("\n".join(out))

print(f"Generated {output_path}")