import json
import os

def to_go_type(prop):
    t = prop.get('type')
    if t == 'string':
        return 'string'
    if t == 'number':
        return 'float64'
    if t == 'integer':
        return 'int'
    if t == 'boolean':
        return 'bool'
    if t == 'array':
        items = prop.get('items', {})
        return '[]' + to_go_type(items)
    return 'interface{}'

def go_field(name):
    parts = name.split('_')
    result = []
    for p in parts:
        upper = p.upper()
        if upper in ('ID', 'DB', 'MM', 'BTU', 'PA', 'KW', 'HZ', 'M2', 'CO2', 'TV'):
            result.append(upper)
        elif p == 'co2':
            result.append('CO2')
        elif p == 'tv':
            result.append('TV')
        else:
            result.append(p.capitalize())
    return ''.join(result)

def collect_filterable_props(tdef, traits):
    props = {}
    for trait_name in tdef.get('traits', []):
        trait = traits.get(trait_name, {})
        for prop_name, prop_schema in trait.get('properties', {}).items():
            if prop_schema.get('filterable'):
                props[prop_name] = prop_schema
    extra = tdef.get('extra_schema', {}).get('properties', {})
    for prop_name, prop_schema in extra.items():
        if prop_schema.get('filterable'):
            props[prop_name] = prop_schema
    return props

def gen_struct(name, props, use_omitempty=True):
    lines = [f"type {name} struct {{"]
    for field, prop in props.items():
        typ = to_go_type(prop)
        go_name = go_field(field)
        tag = f"`json:\"{field},omitempty\"`" if use_omitempty else f"`json:\"{field}\"`"
        lines.append(f"    {go_name} {typ} {tag}")
    lines.append("}")
    return "\n".join(lines)

script_dir = os.path.dirname(__file__)
with open(os.path.join(script_dir, 'device_types.json')) as f:
    data = json.load(f)

traits = data.get('traits', {})
types = data.get('types', {})

out = []
out.append("// Code generated by gen_filters.py; DO NOT EDIT.\n")
out.append("package filters\n")

for type_name, tdef in types.items():
    filterable = collect_filterable_props(tdef, traits)
    struct_name = go_field(type_name) + "Filter"
    if not filterable:
        out.append(f"type {struct_name} struct {{}}\n")
    else:
        out.append(gen_struct(struct_name, filterable))
    out.append("")

aliases = [
    ("CameraFilter", "SmartCameraFilter"),
    ("DoorSensorFilter", "DoorWindowSensorFilter"),
    ("WindowSensorFilter", "DoorWindowSensorFilter"),
    ("SmartSpeaker", "SmartSpeakerFilter"),
    ("Subwoofer", "SubwooferFilter"),
]
for alias, original in aliases:
    out.append(f"type {alias} = {original}\n")

output_path = os.path.join(script_dir, '../../../services/layout/internal/filters/filters_gen.go')
with open(output_path, 'w') as f:
    f.write("\n".join(out))

print(f"Generated {output_path}")
