// Code generated by gen_go.py; DO NOT EDIT.

package device

type Base struct {
    Name string `json:"name"`
    Brand string `json:"brand"`
    Model string `json:"model"`
}

type Connectivity struct {
    Ecosystem []string `json:"ecosystem"`
    Protocol []string `json:"protocol"`
}

type BatteryOperated struct {
    BatteryType *string `json:"battery_type"`
    BatteryLifeMonths *float64 `json:"battery_life_months"`
    Rechargeable *bool `json:"rechargeable"`
}

type IpRated struct {
    IpRating *string `json:"ip_rating"`
}

type Lighting struct {
    PowerWatts float64 `json:"power_watts"`
    VoltageMinWatt float64 `json:"voltage_min_watt"`
    VoltageMaxWatt float64 `json:"voltage_max_watt"`
    LifetimeHours *float64 `json:"lifetime_hours"`
    ColorTemperatureKelvin *float64 `json:"color_temperature_kelvin"`
    ColorRenderingIndex *float64 `json:"color_rendering_index"`
    ColorMode *string `json:"color_mode"`
}

type Sensor struct {
    Accuracy *float64 `json:"accuracy"`
}

type MotionDetection struct {
    DetectionRangeMeters *float64 `json:"detection_range_meters"`
    DetectionAngleDegrees *float64 `json:"detection_angle_degrees"`
}

type WaterLeakSensor struct {
    Name string `json:"name"`
    Brand string `json:"brand"`
    Model string `json:"model"`
    Ecosystem []string `json:"ecosystem"`
    Protocol []string `json:"protocol"`
    BatteryType *string `json:"battery_type"`
    BatteryLifeMonths *float64 `json:"battery_life_months"`
    Rechargeable *bool `json:"rechargeable"`
    IpRating *string `json:"ip_rating"`
    Type interface{} `json:"type"`
    HasAudioAlert *bool `json:"has_audio_alert"`
    AudioAlertVolumeDb *float64 `json:"audio_alert_volume_db"`
    DetectsLeaksAbove *bool `json:"detects_leaks_above"`
    DetectsLeaksBelow *bool `json:"detects_leaks_below"`
    MinDetectedWaterLevelMm *float64 `json:"min_detected_water_level_mm"`
}

type TemperatureSensor struct {
    Name string `json:"name"`
    Brand string `json:"brand"`
    Model string `json:"model"`
    Ecosystem []string `json:"ecosystem"`
    Protocol []string `json:"protocol"`
    BatteryType *string `json:"battery_type"`
    BatteryLifeMonths *float64 `json:"battery_life_months"`
    Rechargeable *bool `json:"rechargeable"`
    IpRating *string `json:"ip_rating"`
    Accuracy *float64 `json:"accuracy"`
    Type interface{} `json:"type"`
    TemperatureMinCelsius float64 `json:"temperature_min_celsius"`
    TemperatureMaxCelsius float64 `json:"temperature_max_celsius"`
    HumiditySensor *bool `json:"humidity_sensor"`
    AccuracyTemperatureCelsius *float64 `json:"accuracy_temperature_celsius"`
    AccuracyHumidityPercent *float64 `json:"accuracy_humidity_percent"`
}

type MotionSensor struct {
    Name string `json:"name"`
    Brand string `json:"brand"`
    Model string `json:"model"`
    Ecosystem []string `json:"ecosystem"`
    Protocol []string `json:"protocol"`
    BatteryType *string `json:"battery_type"`
    BatteryLifeMonths *float64 `json:"battery_life_months"`
    Rechargeable *bool `json:"rechargeable"`
    IpRating *string `json:"ip_rating"`
    DetectionRangeMeters *float64 `json:"detection_range_meters"`
    DetectionAngleDegrees *float64 `json:"detection_angle_degrees"`
    Type interface{} `json:"type"`
}

type SmartLamp struct {
    Name string `json:"name"`
    Brand string `json:"brand"`
    Model string `json:"model"`
    Ecosystem []string `json:"ecosystem"`
    Protocol []string `json:"protocol"`
    PowerWatts float64 `json:"power_watts"`
    VoltageMinWatt float64 `json:"voltage_min_watt"`
    VoltageMaxWatt float64 `json:"voltage_max_watt"`
    LifetimeHours *float64 `json:"lifetime_hours"`
    ColorTemperatureKelvin *float64 `json:"color_temperature_kelvin"`
    ColorRenderingIndex *float64 `json:"color_rendering_index"`
    ColorMode *string `json:"color_mode"`
    Type interface{} `json:"type"`
    MountType *string `json:"mount_type"`
}

type SmartPlug struct {
    Name string `json:"name"`
    Brand string `json:"brand"`
    Model string `json:"model"`
    Ecosystem []string `json:"ecosystem"`
    Protocol []string `json:"protocol"`
    Type interface{} `json:"type"`
    MaxPowerWatts float64 `json:"max_power_watts"`
    VoltageMinWatt float64 `json:"voltage_min_watt"`
    VoltageMaxWatt float64 `json:"voltage_max_watt"`
    UsbPorts *int `json:"usb_ports"`
    ChildLock *bool `json:"child_lock"`
    PowerConsumptionWatts *float64 `json:"power_consumption_watts"`
}
