// Code generated by gen_filters.py; DO NOT EDIT.

package filters

type WaterLeakSensorFilter struct {
    BatteryLifeYears float64 `json:"battery_life_years,omitempty"`
    ProbeType string `json:"probe_type,omitempty"`
    AudioAlertVolumeDB int `json:"audio_alert_volume_db,omitempty"`
}

type SmartLampFilter struct {}


type GasLeakSensorFilter struct {
    BatteryLifeYears float64 `json:"battery_life_years,omitempty"`
    DetectedGas []string `json:"detected_gas,omitempty"`
    AudioAlertVolumeDB int `json:"audio_alert_volume_db,omitempty"`
}

type SmartDoorbellFilter struct {
    BatteryLifeYears float64 `json:"battery_life_years,omitempty"`
    Resolution string `json:"resolution,omitempty"`
    HasNightVision bool `json:"has_night_vision,omitempty"`
    HasTwoWayAudio bool `json:"has_two_way_audio,omitempty"`
    FieldOfViewDeg int `json:"field_of_view_deg,omitempty"`
    DetectionRangeMM float64 `json:"detection_range_mm,omitempty"`
    RecommendedRangeMM float64 `json:"recommended_range_mm,omitempty"`
}

type SmartLockFilter struct {
    BatteryLifeYears float64 `json:"battery_life_years,omitempty"`
    AccessMethods []string `json:"access_methods,omitempty"`
}

type DoorWindowSensorFilter struct {
    BatteryLifeYears float64 `json:"battery_life_years,omitempty"`
}

type MotionSensorFilter struct {
    BatteryLifeYears float64 `json:"battery_life_years,omitempty"`
    DetectionRangeMM float64 `json:"detection_range_mm,omitempty"`
    DetectionAngleDeg float64 `json:"detection_angle_deg,omitempty"`
}

type SmartCameraFilter struct {
    BatteryLifeYears float64 `json:"battery_life_years,omitempty"`
    Resolution string `json:"resolution,omitempty"`
    HasNightVision bool `json:"has_night_vision,omitempty"`
    HasTwoWayAudio bool `json:"has_two_way_audio,omitempty"`
    FieldOfViewDeg int `json:"field_of_view_deg,omitempty"`
    DetectionRangeMM float64 `json:"detection_range_mm,omitempty"`
    RecommendedRangeMM float64 `json:"recommended_range_mm,omitempty"`
}

type SmartSirenFilter struct {
    BatteryLifeYears float64 `json:"battery_life_years,omitempty"`
    MaxVolumeDB int `json:"max_volume_db,omitempty"`
}

type SmartHubFilter struct {}


type TemperatureSensorFilter struct {
    BatteryLifeYears float64 `json:"battery_life_years,omitempty"`
}

type HumiditySensorFilter struct {
    BatteryLifeYears float64 `json:"battery_life_years,omitempty"`
}

type CO2SensorFilter struct {
    BatteryLifeYears float64 `json:"battery_life_years,omitempty"`
}

type SmartRadiatorActuatorFilter struct {
    BatteryLifeYears float64 `json:"battery_life_years,omitempty"`
}

type SmartHumidifierFilter struct {
    TankVolumeLiters float64 `json:"tank_volume_liters,omitempty"`
    ServicedAreaM2 float64 `json:"serviced_area_m2,omitempty"`
}

type AirPurifierFilter struct {
    ServicedAreaM2 float64 `json:"serviced_area_m2,omitempty"`
    HepaFilter bool `json:"hepa_filter,omitempty"`
}

type AirConditionerFilter struct {
    NoiseLevelDB float64 `json:"noise_level_db,omitempty"`
    MaxNoiseLevelDB float64 `json:"max_noise_level_db,omitempty"`
    CoolingPowerBTU float64 `json:"cooling_power_btu,omitempty"`
    CoolingPowerWatts float64 `json:"cooling_power_watts,omitempty"`
    IndoorUnitLengthMM int `json:"indoor_unit_length_mm,omitempty"`
    RecommendedAreaM2 float64 `json:"recommended_area_m2,omitempty"`
}

type SmartFloorThermostatFilter struct {
    MaxLoadKW float64 `json:"max_load_kw,omitempty"`
    CableLength float64 `json:"cable_length,omitempty"`
}

type FloorTemperatureSensorFilter struct {
    BatteryLifeYears float64 `json:"battery_life_years,omitempty"`
    MaxLoadKW float64 `json:"max_load_kw,omitempty"`
    CableLength float64 `json:"cable_length,omitempty"`
}

type RobotVacuumFilter struct {
    NoiseLevelDB float64 `json:"noise_level_db,omitempty"`
    SuctionPowerPA int `json:"suction_power_pa,omitempty"`
    NavigationType string `json:"navigation_type,omitempty"`
    RoomMapping bool `json:"room_mapping,omitempty"`
    WetCleaning bool `json:"wet_cleaning,omitempty"`
    CarpetDetection bool `json:"carpet_detection,omitempty"`
    ObstacleAvoidance bool `json:"obstacle_avoidance,omitempty"`
    AutoEmptyStation bool `json:"auto_empty_station,omitempty"`
    VoiceAssistantSupport bool `json:"voice_assistant_support,omitempty"`
}

type SmartTVFilter struct {
    Resolution string `json:"resolution,omitempty"`
    Width float64 `json:"width,omitempty"`
    RefreshRateHZ int `json:"refresh_rate_hz,omitempty"`
    MaxWidthMM float64 `json:"max_width_mm,omitempty"`
}

type SmartSpeakerFilter struct {}


type SubwooferFilter struct {}


type CeilingSpeakersFilter struct {}


type UnknownFilter struct {}


type CameraFilter = SmartCameraFilter

type DoorSensorFilter = DoorWindowSensorFilter

type WindowSensorFilter = DoorWindowSensorFilter

type SmartSpeaker = SmartSpeakerFilter

type Subwoofer = SubwooferFilter
