INSERT INTO devices (id, brand, model, category, quality, device_attributes, taxonomy_version) VALUES
  (1, 'aqara', 'Leak Sensor', 'water_leak_sensor', 0.86, '{"probe_type":"contact","battery_life_years":2}'::jsonb, 'test'),
  (2, 'aqara', 'Gas Sensor', 'gas_leak_sensor', 0.82, '{"detected_gas":["natural_gas"],"battery_life_years":2}'::jsonb, 'test'),
  (3, 'yandex', 'Smart Bulb', 'smart_lamp', 0.80, '{"socket_type":"E27","wattage_w":8.5,"brightness_lm":800,"dimmable":true}'::jsonb, 'test'),

  (4, 'xiaomi', 'Water Leak Sensor', 'water_leak_sensor', 0.88, '{"probe_type":"cable","battery_life_years":3,"detects_leaks_below":true,"has_audio_alert":true}'::jsonb, 'test'),
  (5, 'tuya', 'Gas Detector', 'gas_leak_sensor', 0.84, '{"detected_gas":["lpg","carbon_monoxide"],"has_audio_alert":true,"battery_life_years":2}'::jsonb, 'test'),
  (6, 'philips', 'Hue White', 'smart_lamp', 0.92, '{"socket_type":"E27","wattage_w":9.0,"brightness_lm":806,"rgb_support":false,"dimmable":true,"color_temp_min_k":2200,"color_temp_max_k":6500}'::jsonb, 'test'),

  (7, 'aqara', 'Video Doorbell G4', 'smart_doorbell', 0.90, '{"has_camera":true,"resolution":"1080p","has_two_way_audio":true,"has_motion_detection":true,"indoor_outdoor":"outdoor"}'::jsonb, 'test'),
  (8, 'ring', 'Video Doorbell 4', 'smart_doorbell', 0.88, '{"has_camera":true,"resolution":"2K","has_night_vision":true,"has_two_way_audio":true,"has_motion_detection":true,"indoor_outdoor":"outdoor","battery_life_years":1}'::jsonb, 'test'),

  (9, 'aqara', 'Smart Lock U100', 'smart_lock', 0.91, '{"access_methods":["keypad","fingerprint","app"],"auto_lock":true,"tamper_alert":true,"battery_life_years":1}'::jsonb, 'test'),
  (10, 'yale', 'Smart Lock', 'smart_lock', 0.85, '{"access_methods":["keypad","key","app"],"auto_lock":true,"door_thickness_min_mm":35,"door_thickness_max_mm":70}'::jsonb, 'test'),

  (11, 'aqara', 'Door/Window Sensor P2', 'door_window_sensor', 0.89, '{"battery_life_years":2,"ip_rating":"IP20"}'::jsonb, 'test'),
  (12, 'sonoff', 'Contact Sensor', 'door_window_sensor', 0.78, '{"battery_life_years":1,"ip_rating":"IP20"}'::jsonb, 'test'),

  (13, 'aqara', 'Motion Sensor P1', 'motion_sensor', 0.87, '{"sensor_type":"pir","detection_range_mm":7000,"detection_angle_deg":120,"battery_life_years":2}'::jsonb, 'test'),
  (14, 'xiaomi', 'Mijia Motion Sensor', 'motion_sensor', 0.80, '{"sensor_type":"pir","detection_range_mm":6000,"detection_angle_deg":100,"has_light_sensor":true,"battery_life_years":2}'::jsonb, 'test'),

  (15, 'aqara', 'Camera Hub G3', 'smart_camera', 0.93, '{"resolution":"2K","has_night_vision":true,"has_two_way_audio":true,"has_motion_detection":true,"has_person_detection":true,"indoor_outdoor":"indoor","ptz":true}'::jsonb, 'test'),
  (16, 'xiaomi', '360 Camera', 'smart_camera', 0.86, '{"resolution":"1080p","has_night_vision":true,"has_two_way_audio":true,"has_motion_detection":true,"indoor_outdoor":"indoor","field_of_view_deg":130}'::jsonb, 'test'),

  (17, 'aqara', 'Siren', 'smart_siren', 0.85, '{"max_volume_db":110,"has_strobe_light":true,"indoor_outdoor":"indoor","battery_life_years":2}'::jsonb, 'test'),
  (18, 'tuya', 'Alarm Siren', 'smart_siren', 0.82, '{"max_volume_db":105,"has_strobe_light":true,"has_tamper_detection":true,"indoor_outdoor":"both"}'::jsonb, 'test'),

  (19, 'aqara', 'Hub M2', 'smart_hub', 0.94, '{"max_connected_devices":128,"has_local_processing":true,"has_ir_blaster":true,"matter_bridge":true,"zigbee_version":"zigbee_3.0"}'::jsonb, 'test'),
  (20, 'xiaomi', 'Gateway 3', 'smart_hub', 0.90, '{"max_connected_devices":100,"has_local_processing":true,"zigbee_version":"zigbee_3.0"}'::jsonb, 'test'),

  (21, 'aqara', 'Temperature Sensor', 'temperature_sensor', 0.88, '{"temp_min_c":-10,"temp_max_c":50,"accuracy_c":0.3,"battery_life_years":2}'::jsonb, 'test'),
  (22, 'xiaomi', 'Temp/Humidity Sensor', 'temperature_sensor', 0.84, '{"temp_min_c":0,"temp_max_c":60,"accuracy_c":0.5,"battery_life_years":2}'::jsonb, 'test'),

  (23, 'sonoff', 'Humidity Sensor', 'humidity_sensor', 0.80, '{"humidity_range_min_percent":0,"humidity_range_max_percent":100,"battery_life_years":2}'::jsonb, 'test'),
  (24, 'tuya', 'Humidity Detector', 'humidity_sensor', 0.78, '{"humidity_range_min_percent":10,"humidity_range_max_percent":90,"battery_life_years":1}'::jsonb, 'test'),

  (25, 'aqara', 'CO2 Sensor', 'co2_sensor', 0.86, '{"co2_range_min_ppm":400,"co2_range_max_ppm":5000,"battery_life_years":2}'::jsonb, 'test'),
  (26, 'xiaomi', 'Air Quality Monitor', 'co2_sensor', 0.82, '{"co2_range_min_ppm":300,"co2_range_max_ppm":10000,"battery_life_years":1}'::jsonb, 'test'),

  (27, 'aqara', 'Radiator Thermostat E1', 'smart_radiator_actuator', 0.87, '{"battery_life_years":2}'::jsonb, 'test'),
  (28, 'tuya', 'Radiator Valve', 'smart_radiator_actuator', 0.80, '{"battery_life_years":1}'::jsonb, 'test'),

  (29, 'xiaomi', 'Smart Humidifier', 'smart_humidifier', 0.90, '{"tank_volume_l":4.5,"serviced_area_m2":25,"power_source":["mains"]}'::jsonb, 'test'),
  (30, 'philips', 'Humidifier', 'smart_humidifier', 0.88, '{"tank_volume_l":3.0,"serviced_area_m2":20,"power_source":["mains"]}'::jsonb, 'test'),

  (31, 'xiaomi', 'Air Purifier 4', 'air_purifier', 0.92, '{"serviced_area_m2":40,"hepa_filter":true,"power_source":["mains"]}'::jsonb, 'test'),
  (32, 'philips', 'Air Purifier', 'air_purifier', 0.89, '{"serviced_area_m2":35,"hepa_filter":true,"power_source":["mains"]}'::jsonb, 'test'),

  (33, 'xiaomi', 'Smart AC', 'air_conditioner', 0.88, '{"cooling_power_btu":12000,"noise_level_db":45,"recommended_area_m2":25,"power_source":["mains"]}'::jsonb, 'test'),
  (34, 'gree', 'Smart AC', 'air_conditioner', 0.85, '{"cooling_power_btu":9000,"noise_level_db":40,"recommended_area_m2":20,"power_source":["mains"]}'::jsonb, 'test'),

  (35, 'aqara', 'Floor Thermostat', 'smart_floor_thermostat', 0.86, '{"max_load_kw":3.0,"power_source":["mains"]}'::jsonb, 'test'),
  (36, 'tuya', 'Floor Thermostat', 'smart_floor_thermostat', 0.80, '{"max_load_kw":2.5,"power_source":["mains"]}'::jsonb, 'test'),

  (37, 'aqara', 'Floor Sensor', 'floor_temperature_sensor', 0.84, '{"max_load_kw":3.0,"cable_length_mm":3000,"power_source":["mains"]}'::jsonb, 'test'),
  (38, 'xiaomi', 'Floor Sensor', 'floor_temperature_sensor', 0.78, '{"max_load_kw":2.5,"cable_length_mm":5000,"power_source":["mains"]}'::jsonb, 'test'),

  (39, 'xiaomi', 'Robot Vacuum', 'robot_vacuum', 0.91, '{"suction_power_pa":4000,"navigation_type":"lidar","room_mapping":true,"wet_cleaning":true,"carpet_detection":true,"obstacle_avoidance":true,"power_source":["rechargeable_battery"]}'::jsonb, 'test'),
  (40, 'roborock', 'S7', 'robot_vacuum', 0.95, '{"suction_power_pa":6000,"navigation_type":"lidar_ai","room_mapping":true,"wet_cleaning":true,"carpet_detection":true,"auto_empty_station":true,"power_source":["rechargeable_battery"]}'::jsonb, 'test'),

  (41, 'xiaomi', 'Smart TV', 'smart_tv', 0.87, '{"resolution":"4K","refresh_rate_hz":60,"width_mm":1450,"power_source":["mains"]}'::jsonb, 'test'),
  (42, 'samsung', 'Smart TV', 'smart_tv', 0.90, '{"resolution":"4K","refresh_rate_hz":120,"width_mm":1670,"power_source":["mains"]}'::jsonb, 'test'),

  (43, 'yandex', 'Station', 'smart_speaker', 0.85, '{"power_source":["mains"]}'::jsonb, 'test'),
  (44, 'google', 'Nest Audio', 'smart_speaker', 0.88, '{"power_source":["mains"]}'::jsonb, 'test'),

  (45, 'xiaomi', 'Subwoofer', 'subwoofer', 0.80, '{"power_source":["mains"]}'::jsonb, 'test'),
  (46, 'sony', 'Subwoofer', 'subwoofer', 0.82, '{"power_source":["mains"]}'::jsonb, 'test'),

  (47, 'sonos', 'Ceiling Speaker', 'ceiling_speakers', 0.75, '{}'::jsonb, 'test'),
  (48, 'yamaha', 'Ceiling Speaker', 'ceiling_speakers', 0.70, '{}'::jsonb, 'test')
ON CONFLICT (id) DO UPDATE SET
  brand = EXCLUDED.brand,
  model = EXCLUDED.model,
  category = EXCLUDED.category,
  quality = EXCLUDED.quality,
  device_attributes = EXCLUDED.device_attributes,
  taxonomy_version = EXCLUDED.taxonomy_version;


INSERT INTO parsed_listing_snapshots (
  id, extracted_in_stock, extracted_text, extracted_name, extracted_brand,
  extracted_price, extracted_currency, extracted_category, extracted_rating,
  extracted_review_count
) VALUES
  (1, true, 'Leak Sensor', 'Leak Sensor', 'Aqara', 1200, 'RUB', 'water_leak_sensor', 4.7, 120),
  (2, true, 'Gas Sensor', 'Gas Sensor', 'Aqara', 2200, 'RUB', 'gas_leak_sensor', 4.6, 80),
  (3, true, 'Smart Bulb', 'Smart Bulb', 'Yandex', 900, 'RUB', 'smart_lamp', 4.5, 200),
  (4, true, 'Water Leak Sensor', 'Water Leak Sensor', 'Xiaomi', 1500, 'RUB', 'water_leak_sensor', 4.8, 150),
  (5, true, 'Gas Detector', 'Gas Detector', 'Tuya', 2500, 'RUB', 'gas_leak_sensor', 4.4, 60),
  (6, true, 'Hue White', 'Hue White', 'Philips', 1500, 'RUB', 'smart_lamp', 4.9, 300),
  (7, true, 'Video Doorbell G4', 'Video Doorbell G4', 'Aqara', 8000, 'RUB', 'smart_doorbell', 4.8, 90),
  (8, true, 'Video Doorbell 4', 'Video Doorbell 4', 'Ring', 12000, 'RUB', 'smart_doorbell', 4.7, 200),
  (9, true, 'Smart Lock U100', 'Smart Lock U100', 'Aqara', 15000, 'RUB', 'smart_lock', 4.9, 50),
  (10, true, 'Smart Lock', 'Smart Lock', 'Yale', 10000, 'RUB', 'smart_lock', 4.5, 80),
  (11, true, 'Door/Window Sensor P2', 'Door/Window Sensor P2', 'Aqara', 2000, 'RUB', 'door_window_sensor', 4.6, 110),
  (12, true, 'Contact Sensor', 'Contact Sensor', 'Sonoff', 1500, 'RUB', 'door_window_sensor', 4.3, 70),
  (13, true, 'Motion Sensor P1', 'Motion Sensor P1', 'Aqara', 2500, 'RUB', 'motion_sensor', 4.7, 130),
  (14, true, 'Mijia Motion Sensor', 'Mijia Motion Sensor', 'Xiaomi', 1800, 'RUB', 'motion_sensor', 4.5, 100),
  (15, true, 'Camera Hub G3', 'Camera Hub G3', 'Aqara', 10000, 'RUB', 'smart_camera', 4.9, 40),
  (16, true, '360 Camera', '360 Camera', 'Xiaomi', 7000, 'RUB', 'smart_camera', 4.6, 60),
  (17, true, 'Siren', 'Siren', 'Aqara', 3000, 'RUB', 'smart_siren', 4.5, 50),
  (18, true, 'Alarm Siren', 'Alarm Siren', 'Tuya', 2500, 'RUB', 'smart_siren', 4.2, 30),
  (19, true, 'Hub M2', 'Hub M2', 'Aqara', 5000, 'RUB', 'smart_hub', 4.8, 80),
  (20, true, 'Gateway 3', 'Gateway 3', 'Xiaomi', 4000, 'RUB', 'smart_hub', 4.7, 70),
  (21, true, 'Temperature Sensor', 'Temperature Sensor', 'Aqara', 1800, 'RUB', 'temperature_sensor', 4.6, 90),
  (22, true, 'Temp/Humidity Sensor', 'Temp/Humidity Sensor', 'Xiaomi', 1600, 'RUB', 'temperature_sensor', 4.5, 80),
  (23, true, 'Humidity Sensor', 'Humidity Sensor', 'Sonoff', 1200, 'RUB', 'humidity_sensor', 4.3, 40),
  (24, true, 'Humidity Detector', 'Humidity Detector', 'Tuya', 1400, 'RUB', 'humidity_sensor', 4.2, 35),
  (25, true, 'CO2 Sensor', 'CO2 Sensor', 'Aqara', 3000, 'RUB', 'co2_sensor', 4.7, 45),
  (26, true, 'Air Quality Monitor', 'Air Quality Monitor', 'Xiaomi', 2500, 'RUB', 'co2_sensor', 4.5, 50),
  (27, true, 'Radiator Thermostat E1', 'Radiator Thermostat E1', 'Aqara', 4000, 'RUB', 'smart_radiator_actuator', 4.8, 60),
  (28, true, 'Radiator Valve', 'Radiator Valve', 'Tuya', 3500, 'RUB', 'smart_radiator_actuator', 4.4, 40),
  (29, true, 'Smart Humidifier', 'Smart Humidifier', 'Xiaomi', 6000, 'RUB', 'smart_humidifier', 4.7, 70),
  (30, true, 'Humidifier', 'Humidifier', 'Philips', 5000, 'RUB', 'smart_humidifier', 4.6, 60),
  (31, true, 'Air Purifier 4', 'Air Purifier 4', 'Xiaomi', 8000, 'RUB', 'air_purifier', 4.8, 100),
  (32, true, 'Air Purifier', 'Air Purifier', 'Philips', 7000, 'RUB', 'air_purifier', 4.7, 80),
  (33, true, 'Smart AC', 'Smart AC', 'Xiaomi', 30000, 'RUB', 'air_conditioner', 4.6, 30),
  (34, true, 'Smart AC', 'Smart AC', 'Gree', 25000, 'RUB', 'air_conditioner', 4.5, 25),
  (35, true, 'Floor Thermostat', 'Floor Thermostat', 'Aqara', 4500, 'RUB', 'smart_floor_thermostat', 4.6, 20),
  (36, true, 'Floor Thermostat', 'Floor Thermostat', 'Tuya', 4000, 'RUB', 'smart_floor_thermostat', 4.4, 15),
  (37, true, 'Floor Sensor', 'Floor Sensor', 'Aqara', 3000, 'RUB', 'floor_temperature_sensor', 4.5, 10),
  (38, true, 'Floor Sensor', 'Floor Sensor', 'Xiaomi', 2800, 'RUB', 'floor_temperature_sensor', 4.3, 8),
  (39, true, 'Robot Vacuum', 'Robot Vacuum', 'Xiaomi', 25000, 'RUB', 'robot_vacuum', 4.8, 150),
  (40, true, 'S7', 'S7', 'Roborock', 35000, 'RUB', 'robot_vacuum', 4.9, 200),
  (41, true, 'Smart TV', 'Smart TV', 'Xiaomi', 40000, 'RUB', 'smart_tv', 4.6, 40),
  (42, true, 'Smart TV', 'Smart TV', 'Samsung', 60000, 'RUB', 'smart_tv', 4.8, 60),
  (43, true, 'Station', 'Station', 'Yandex', 10000, 'RUB', 'smart_speaker', 4.5, 90),
  (44, true, 'Nest Audio', 'Nest Audio', 'Google', 8000, 'RUB', 'smart_speaker', 4.7, 120),
  (45, true, 'Subwoofer', 'Subwoofer', 'Xiaomi', 15000, 'RUB', 'subwoofer', 4.4, 30),
  (46, true, 'Subwoofer', 'Subwoofer', 'Sony', 20000, 'RUB', 'subwoofer', 4.6, 25),
  (47, true, 'Ceiling Speaker', 'Ceiling Speaker', 'Sonos', 12000, 'RUB', 'ceiling_speakers', 4.3, 15),
  (48, true, 'Ceiling Speaker', 'Ceiling Speaker', 'Yamaha', 10000, 'RUB', 'ceiling_speakers', 4.2, 10)
ON CONFLICT (id) DO UPDATE SET
  extracted_in_stock = EXCLUDED.extracted_in_stock,
  extracted_text = EXCLUDED.extracted_text,
  extracted_name = EXCLUDED.extracted_name,
  extracted_brand = EXCLUDED.extracted_brand,
  extracted_price = EXCLUDED.extracted_price,
  extracted_currency = EXCLUDED.extracted_currency,
  extracted_category = EXCLUDED.extracted_category,
  extracted_rating = EXCLUDED.extracted_rating,
  extracted_review_count = EXCLUDED.extracted_review_count;

INSERT INTO llm_extracted_listings (
  id, parsed_listing_snapshot_id, brand, model, category,
  category_confidence, device_attributes, taxonomy_version, llm_model
) VALUES
  (1, 1, 'Aqara', 'Leak Sensor', 'water_leak_sensor', 1.0, '{}'::jsonb, 'test', 'seed'),
  (2, 2, 'Aqara', 'Gas Sensor', 'gas_leak_sensor', 1.0, '{}'::jsonb, 'test', 'seed'),
  (3, 3, 'Yandex', 'Smart Bulb', 'smart_lamp', 1.0, '{}'::jsonb, 'test', 'seed'),
  (4, 4, 'Xiaomi', 'Water Leak Sensor', 'water_leak_sensor', 1.0, '{}'::jsonb, 'test', 'seed'),
  (5, 5, 'Tuya', 'Gas Detector', 'gas_leak_sensor', 1.0, '{}'::jsonb, 'test', 'seed'),
  (6, 6, 'Philips', 'Hue White', 'smart_lamp', 1.0, '{}'::jsonb, 'test', 'seed'),
  (7, 7, 'Aqara', 'Video Doorbell G4', 'smart_doorbell', 1.0, '{}'::jsonb, 'test', 'seed'),
  (8, 8, 'Ring', 'Video Doorbell 4', 'smart_doorbell', 1.0, '{}'::jsonb, 'test', 'seed'),
  (9, 9, 'Aqara', 'Smart Lock U100', 'smart_lock', 1.0, '{}'::jsonb, 'test', 'seed'),
  (10, 10, 'Yale', 'Smart Lock', 'smart_lock', 1.0, '{}'::jsonb, 'test', 'seed'),
  (11, 11, 'Aqara', 'Door/Window Sensor P2', 'door_window_sensor', 1.0, '{}'::jsonb, 'test', 'seed'),
  (12, 12, 'Sonoff', 'Contact Sensor', 'door_window_sensor', 1.0, '{}'::jsonb, 'test', 'seed'),
  (13, 13, 'Aqara', 'Motion Sensor P1', 'motion_sensor', 1.0, '{}'::jsonb, 'test', 'seed'),
  (14, 14, 'Xiaomi', 'Mijia Motion Sensor', 'motion_sensor', 1.0, '{}'::jsonb, 'test', 'seed'),
  (15, 15, 'Aqara', 'Camera Hub G3', 'smart_camera', 1.0, '{}'::jsonb, 'test', 'seed'),
  (16, 16, 'Xiaomi', '360 Camera', 'smart_camera', 1.0, '{}'::jsonb, 'test', 'seed'),
  (17, 17, 'Aqara', 'Siren', 'smart_siren', 1.0, '{}'::jsonb, 'test', 'seed'),
  (18, 18, 'Tuya', 'Alarm Siren', 'smart_siren', 1.0, '{}'::jsonb, 'test', 'seed'),
  (19, 19, 'Aqara', 'Hub M2', 'smart_hub', 1.0, '{}'::jsonb, 'test', 'seed'),
  (20, 20, 'Xiaomi', 'Gateway 3', 'smart_hub', 1.0, '{}'::jsonb, 'test', 'seed'),
  (21, 21, 'Aqara', 'Temperature Sensor', 'temperature_sensor', 1.0, '{}'::jsonb, 'test', 'seed'),
  (22, 22, 'Xiaomi', 'Temp/Humidity Sensor', 'temperature_sensor', 1.0, '{}'::jsonb, 'test', 'seed'),
  (23, 23, 'Sonoff', 'Humidity Sensor', 'humidity_sensor', 1.0, '{}'::jsonb, 'test', 'seed'),
  (24, 24, 'Tuya', 'Humidity Detector', 'humidity_sensor', 1.0, '{}'::jsonb, 'test', 'seed'),
  (25, 25, 'Aqara', 'CO2 Sensor', 'co2_sensor', 1.0, '{}'::jsonb, 'test', 'seed'),
  (26, 26, 'Xiaomi', 'Air Quality Monitor', 'co2_sensor', 1.0, '{}'::jsonb, 'test', 'seed'),
  (27, 27, 'Aqara', 'Radiator Thermostat E1', 'smart_radiator_actuator', 1.0, '{}'::jsonb, 'test', 'seed'),
  (28, 28, 'Tuya', 'Radiator Valve', 'smart_radiator_actuator', 1.0, '{}'::jsonb, 'test', 'seed'),
  (29, 29, 'Xiaomi', 'Smart Humidifier', 'smart_humidifier', 1.0, '{}'::jsonb, 'test', 'seed'),
  (30, 30, 'Philips', 'Humidifier', 'smart_humidifier', 1.0, '{}'::jsonb, 'test', 'seed'),
  (31, 31, 'Xiaomi', 'Air Purifier 4', 'air_purifier', 1.0, '{}'::jsonb, 'test', 'seed'),
  (32, 32, 'Philips', 'Air Purifier', 'air_purifier', 1.0, '{}'::jsonb, 'test', 'seed'),
  (33, 33, 'Xiaomi', 'Smart AC', 'air_conditioner', 1.0, '{}'::jsonb, 'test', 'seed'),
  (34, 34, 'Gree', 'Smart AC', 'air_conditioner', 1.0, '{}'::jsonb, 'test', 'seed'),
  (35, 35, 'Aqara', 'Floor Thermostat', 'smart_floor_thermostat', 1.0, '{}'::jsonb, 'test', 'seed'),
  (36, 36, 'Tuya', 'Floor Thermostat', 'smart_floor_thermostat', 1.0, '{}'::jsonb, 'test', 'seed'),
  (37, 37, 'Aqara', 'Floor Sensor', 'floor_temperature_sensor', 1.0, '{}'::jsonb, 'test', 'seed'),
  (38, 38, 'Xiaomi', 'Floor Sensor', 'floor_temperature_sensor', 1.0, '{}'::jsonb, 'test', 'seed'),
  (39, 39, 'Xiaomi', 'Robot Vacuum', 'robot_vacuum', 1.0, '{}'::jsonb, 'test', 'seed'),
  (40, 40, 'Roborock', 'S7', 'robot_vacuum', 1.0, '{}'::jsonb, 'test', 'seed'),
  (41, 41, 'Xiaomi', 'Smart TV', 'smart_tv', 1.0, '{}'::jsonb, 'test', 'seed'),
  (42, 42, 'Samsung', 'Smart TV', 'smart_tv', 1.0, '{}'::jsonb, 'test', 'seed'),
  (43, 43, 'Yandex', 'Station', 'smart_speaker', 1.0, '{}'::jsonb, 'test', 'seed'),
  (44, 44, 'Google', 'Nest Audio', 'smart_speaker', 1.0, '{}'::jsonb, 'test', 'seed'),
  (45, 45, 'Xiaomi', 'Subwoofer', 'subwoofer', 1.0, '{}'::jsonb, 'test', 'seed'),
  (46, 46, 'Sony', 'Subwoofer', 'subwoofer', 1.0, '{}'::jsonb, 'test', 'seed'),
  (47, 47, 'Sonos', 'Ceiling Speaker', 'ceiling_speakers', 1.0, '{}'::jsonb, 'test', 'seed'),
  (48, 48, 'Yamaha', 'Ceiling Speaker', 'ceiling_speakers', 1.0, '{}'::jsonb, 'test', 'seed')
ON CONFLICT (id) DO UPDATE SET
  parsed_listing_snapshot_id = EXCLUDED.parsed_listing_snapshot_id,
  brand = EXCLUDED.brand,
  model = EXCLUDED.model,
  category = EXCLUDED.category,
  category_confidence = EXCLUDED.category_confidence,
  device_attributes = EXCLUDED.device_attributes,
  taxonomy_version = EXCLUDED.taxonomy_version,
  llm_model = EXCLUDED.llm_model;

INSERT INTO listing_device_links (llm_extracted_listing_id, device_id) VALUES
  (1, 1),
  (2, 2),
  (3, 3),
  (4, 4),
  (5, 5),
  (6, 6),
  (7, 7),
  (8, 8),
  (9, 9),
  (10, 10),
  (11, 11),
  (12, 12),
  (13, 13),
  (14, 14),
  (15, 15),
  (16, 16),
  (17, 17),
  (18, 18),
  (19, 19),
  (20, 20),
  (21, 21),
  (22, 22),
  (23, 23),
  (24, 24),
  (25, 25),
  (26, 26),
  (27, 27),
  (28, 28),
  (29, 29),
  (30, 30),
  (31, 31),
  (32, 32),
  (33, 33),
  (34, 34),
  (35, 35),
  (36, 36),
  (37, 37),
  (38, 38),
  (39, 39),
  (40, 40),
  (41, 41),
  (42, 42),
  (43, 43),
  (44, 44),
  (45, 45),
  (46, 46),
  (47, 47),
  (48, 48)
ON CONFLICT (llm_extracted_listing_id) DO UPDATE SET
  device_id = EXCLUDED.device_id;

INSERT INTO direct_compatibility (device_id, ecosystem, protocol) VALUES
  (1, 'yandex', 'zigbee'),
  (2, 'yandex', 'zigbee'),
  (3, 'yandex', 'wifi'),
  (4, 'yandex', 'zigbee'),
  (5, 'yandex', 'wifi'),
  (6, 'yandex', 'zigbee'),
  (7, 'yandex', 'wifi'),
  (8, 'yandex', 'wifi'),
  (9, 'yandex', 'zigbee'),
  (10, 'yandex', 'wifi'),
  (11, 'yandex', 'zigbee'),
  (12, 'yandex', 'wifi'),
  (13, 'yandex', 'zigbee'),
  (14, 'yandex', 'zigbee'),
  (15, 'yandex', 'wifi'),
  (16, 'yandex', 'wifi'),
  (17, 'yandex', 'zigbee'),
  (18, 'yandex', 'wifi'),
  (19, 'yandex', 'wifi'),
  (20, 'yandex', 'wifi'),
  (21, 'yandex', 'zigbee'),
  (22, 'yandex', 'zigbee'),
  (23, 'yandex', 'wifi'),
  (24, 'yandex', 'wifi'),
  (25, 'yandex', 'zigbee'),
  (26, 'yandex', 'wifi'),
  (27, 'yandex', 'zigbee'),
  (28, 'yandex', 'wifi'),
  (29, 'yandex', 'wifi'),
  (30, 'yandex', 'wifi'),
  (31, 'yandex', 'wifi'),
  (32, 'yandex', 'wifi'),
  (33, 'yandex', 'wifi'),
  (34, 'yandex', 'wifi'),
  (35, 'yandex', 'wifi'),
  (36, 'yandex', 'wifi'),
  (37, 'yandex', 'wifi'),
  (38, 'yandex', 'wifi'),
  (39, 'yandex', 'wifi'),
  (40, 'yandex', 'wifi'),
  (41, 'yandex', 'wifi'),
  (42, 'yandex', 'wifi'),
  (43, 'yandex', 'wifi'),
  (44, 'yandex', 'wifi'),
  (45, 'yandex', 'wifi'),
  (46, 'yandex', 'wifi')
ON CONFLICT (device_id, ecosystem, protocol) DO NOTHING;
