// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package worker

import (
	"context"

	"github.com/Intelligent-Smart-Home-Design-System/monorepo/services/scraper/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockScraper creates a new instance of MockScraper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScraper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScraper {
	mock := &MockScraper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScraper is an autogenerated mock type for the Scraper type
type MockScraper struct {
	mock.Mock
}

type MockScraper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScraper) EXPECT() *MockScraper_Expecter {
	return &MockScraper_Expecter{mock: &_m.Mock}
}

// Scrape provides a mock function for the type MockScraper
func (_mock *MockScraper) Scrape(ctx context.Context, task domain.ScrapeTask) (domain.ScrapeResult, error) {
	ret := _mock.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Scrape")
	}

	var r0 domain.ScrapeResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ScrapeTask) (domain.ScrapeResult, error)); ok {
		return returnFunc(ctx, task)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ScrapeTask) domain.ScrapeResult); ok {
		r0 = returnFunc(ctx, task)
	} else {
		r0 = ret.Get(0).(domain.ScrapeResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ScrapeTask) error); ok {
		r1 = returnFunc(ctx, task)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScraper_Scrape_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scrape'
type MockScraper_Scrape_Call struct {
	*mock.Call
}

// Scrape is a helper method to define mock.On call
//   - ctx context.Context
//   - task domain.ScrapeTask
func (_e *MockScraper_Expecter) Scrape(ctx interface{}, task interface{}) *MockScraper_Scrape_Call {
	return &MockScraper_Scrape_Call{Call: _e.mock.On("Scrape", ctx, task)}
}

func (_c *MockScraper_Scrape_Call) Run(run func(ctx context.Context, task domain.ScrapeTask)) *MockScraper_Scrape_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ScrapeTask
		if args[1] != nil {
			arg1 = args[1].(domain.ScrapeTask)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScraper_Scrape_Call) Return(scrapeResult domain.ScrapeResult, err error) *MockScraper_Scrape_Call {
	_c.Call.Return(scrapeResult, err)
	return _c
}

func (_c *MockScraper_Scrape_Call) RunAndReturn(run func(ctx context.Context, task domain.ScrapeTask) (domain.ScrapeResult, error)) *MockScraper_Scrape_Call {
	_c.Call.Return(run)
	return _c
}
